//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPlannerV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TP
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Display (Name="Phone Number")]
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        [Display (Name="Start Date")]
        public System.DateTime StartDate { get; set; }
        [Display (Name="End Date")]
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Budget { get; set; }
        [Display (Name="Other Requirements")]
        public string OtherRequests { get; set; }
        [Display (Name="User Name")]
        public string UserName { get; set; }
    }
}
