//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPlannerV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelPlanner
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Event { get; set; }
        public string Notes { get; set; }
        public string UserName { get; set; }
    }
}
